(() => {
const root=document.getElementById('dailyReportRoot'); if(!root)return;
const KEY='qa_daily_report_v1', HIST='qa_daily_report_history_v1';
const today=()=>new Date().toISOString().slice(0,10), nowTime=()=>new Date().toTimeString().slice(0,5), uid=()=>crypto.randomUUID?.()||Date.now()+'_'+Math.random();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const requesters=['','Alan','Ygor','Jefferson','Lucas'];
const recordStatuses=['Pendente','Concluído','Indefinido'];
const brandOptions=current=>{
 let stored=[];try{stored=JSON.parse(localStorage.getItem('fvp-brand-ispb-base-v1')||'[]')}catch{stored=[]}
 let rows=stored.length?stored:(window.DEFAULT_ISPB_ROWS||[]);
 let brands=[...new Set(rows.map(row=>String(row.brand||row.Marca||row.marca||row.Brand||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
 if(current&&!brands.includes(current))brands.unshift(current);
 return ['',...brands];
};
const empty=()=>({meta:{title:'Relatório Diário de Solicitações e Demandas',objective:'Centralizar informações diárias de solicitações, demandas, ocorrências e acompanhamentos',audience:'Gestão',version:'1.0',date:today(),classification:'Uso interno',owner:'',team:'Serviços',company:'Chicago Advisory',notes:'',logo:'./assets/versao png.png'},records:[],customCategories:[],savedAt:null,dirty:false});
let state; try{state=JSON.parse(localStorage.getItem(KEY))||empty()}catch{state=empty()} state.meta={...empty().meta,...state.meta}; state.records=state.records||[]; if(!state.meta.logo||state.meta.logo==='./assets/logo.avif')state.meta.logo='./assets/versao png.png';
const save=(silent=true)=>{state.savedAt=new Date().toISOString();state.dirty=false;localStorage.setItem(KEY,JSON.stringify(state));renderHeader();if(!silent)toast('Rascunho salvo com sucesso.')};
const toast=m=>{let e=document.createElement('div');e.className='dr-toast';e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),2600)};
const formatDate=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'';
root.innerHTML=`<div class="dr"><header class="dr-top"><div><h1>Relatório Diário</h1><p>Registro contínuo, consolidação e relatório executivo.</p><span id="drSaved" class="dr-save"></span></div><div class="dr-actions"><button class="dr-btn" data-act="meta">Informações gerais</button><button class="dr-btn" data-act="history">Histórico</button><button class="dr-btn" data-act="save">Salvar rascunho</button><button class="dr-btn" data-act="preview">Visualizar relatório</button><button class="dr-btn primary" data-act="pdf">Gerar PDF</button></div></header><section class="dr-grid"><article class="dr-kpi"><span>Registros do dia</span><strong id="drTotal">0</strong></article><article class="dr-kpi"><span>Pendentes</span><strong id="drPending">0</strong></article><article class="dr-kpi"><span>Concluídos</span><strong id="drDone">0</strong></article></section><section class="dr-panel"><div class="dr-panel-head"><div><h2 id="drDate"></h2><p class="dr-note" id="drOwner"></p></div><div class="dr-actions"><select id="drSort" class="dr-btn"><option value="manual">Ordem manual</option><option value="time">Horário</option></select><button class="dr-btn" data-act="review">Revisar conteúdo com IA</button><button class="dr-btn primary" data-act="new">Adicionar novo registro</button></div></div><div id="drList" class="dr-list"></div></section></div><div id="drModal" class="dr-modal" hidden><div id="drModalBox" class="dr-modal-box"></div></div>`;
const modal=document.getElementById('drModal'), box=document.getElementById('drModalBox');
function renderHeader(){document.getElementById('drSaved').textContent=state.savedAt?'Salvo automaticamente em '+new Date(state.savedAt).toLocaleString('pt-BR'):'Ainda não salvo';document.getElementById('drDate').textContent='Registros de '+formatDate(state.meta.date);document.getElementById('drOwner').textContent=state.meta.owner?`Responsável: ${state.meta.owner} • ${state.meta.team}`:'Informe o responsável em “Informações gerais”';document.getElementById('drTotal').textContent=state.records.length;document.getElementById('drPending').textContent=state.records.filter(r=>r.status!=='Concluído').length;document.getElementById('drDone').textContent=state.records.filter(r=>r.status==='Concluído').length}
function renderList(){let sort=document.getElementById('drSort').value, list=[...state.records];if(sort==='time')list.sort((a,b)=>(a.time||'').localeCompare(b.time||''));if(sort==='priority'){let p={Alta:0,Média:1,Baixa:2};list.sort((a,b)=>(p[a.priority]??3)-(p[b.priority]??3))}document.getElementById('drList').innerHTML=list.length?list.map((r,index)=>`<article class="dr-item" draggable="true" data-id="${r.id}"><span class="dr-handle"><b>${index+1}</b><small>⋮⋮</small></span><div><h3>${esc(recordTitle(r))}</h3><div class="dr-meta">${r.requester?`<span class="dr-badge">${esc(r.requester)}</span>`:''}${r.ticket?`<span class="dr-badge">Ticket ${esc(r.ticket)}</span>`:''}${r.institution?`<span class="dr-badge">${esc(r.institution)}</span>`:''}${r.date?`<span class="dr-badge">${formatDate(r.date)}</span>`:''}<span class="dr-badge ${statusClass(r.status)}">${esc(r.status)}</span></div><p>${esc(recordDescription(r))}</p></div><div class="dr-card-actions"><button class="dr-btn" data-row="edit">Editar</button><button class="dr-btn" data-row="duplicate">Duplicar</button><button class="dr-btn" data-row="toggle">${r.status==='Concluído'?'Reabrir':'Concluir'}</button><button class="dr-btn danger" data-row="delete">Excluir</button></div></article>`).join(''):'<div class="dr-empty">Nenhum registro cadastrado. Use “Adicionar novo registro” para começar.</div>';renderHeader();bindDrag()}
const field=(name,label,type='text',value='',cls='',required=false,options=[])=>`<div class="dr-field ${cls}" data-field="${name}"><label>${label}${required?' *':''}</label>${type==='textarea'?`<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea>`:type==='select'?`<select name="${name}" ${required?'required':''}>${options.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}>`}<small class="dr-error">Campo obrigatório</small></div>`;
const datalistField=(name,label,value='',options=[],cls='',required=false)=>`<div class="dr-field ${cls}" data-field="${name}"><label>${label}${required?' *':''}</label><input name="${name}" type="text" value="${esc(value)}" list="${name}Options" ${required?'required':''}> <datalist id="${name}Options">${options.filter(Boolean).map(x=>`<option value="${esc(x)}"></option>`).join('')}</datalist><small class="dr-error">Campo obrigatório</small></div>`;
const statusClass=value=>'status-'+String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const recordTitle=r=>r.testName||r.title||r.ticket||'Registro sem nome';
const recordDescription=r=>r.description||r.notes||'';
function organizeRecordForm(form){
 const groups=[
  ['Dados da solicitação',['requester','ticket','institution','testName','date','status','description','evidenceLink']]
 ];
 const source=form.querySelector(':scope > .dr-form-grid'); if(!source)return;
 groups.forEach(([title,names])=>{const section=document.createElement('section');section.className='dr-form-section';section.innerHTML=`<h3 class="dr-form-section-title">${title}</h3><div class="dr-form-section-body dr-form-grid"></div>`;const body=section.lastElementChild;names.forEach(name=>{const item=source.querySelector(`[data-field="${name}"]`);if(item)body.appendChild(item)});if(body.children.length)form.insertBefore(section,source)});source.remove();
}
function openRecord(rec={}){let r={date:state.meta.date,time:nowTime(),status:'Pendente',priority:'Média',category:'Solicitação de apoio',...rec};box.innerHTML=`<div class="dr-panel-head"><h2>${r.id?'Editar':'Adicionar'} registro</h2><button class="dr-btn" data-close>Fechar</button></div><form id="drRecordForm"><div class="dr-form-grid">${field('requester','Nome do solicitante','select',r.requester,'',true,requesters)}${field('ticket','Ticket','text',r.ticket,'',true)}${datalistField('institution','Marca',r.institution,brandOptions(r.institution),'',true)}${field('testName','Nome do teste','text',r.testName||r.title,'wide',true)}${field('date','Data da solicitação','date',r.date,'',true)}${field('status','Status do relatório','select',r.status||'Pendente','',true,recordStatuses)}${field('description','Mensagem sobre o que foi tratada','textarea',recordDescription(r),'full',true)}${field('evidenceLink','Link','url',r.evidenceLink||r.link||'','full')}</div><div class="dr-modal-foot"><button type="button" class="dr-btn" data-close>Cancelar</button><button class="dr-btn primary" type="submit">Salvar registro</button></div></form>`;organizeRecordForm(box.querySelector('#drRecordForm'));modal.hidden=false;box.querySelector('form').onsubmit=e=>{e.preventDefault();let invalid=[...e.target.querySelectorAll('[required]')].filter(i=>!i.value.trim());e.target.querySelectorAll('.invalid').forEach(x=>x.classList.remove('invalid'));if(invalid.length){invalid.forEach(i=>i.closest('.dr-field').classList.add('invalid'));invalid[0].focus();toast('Existem campos obrigatórios pendentes.');return}let data=Object.fromEntries(new FormData(e.target));let saved={...r,...data,title:data.testName,category:r.category||'Solicitação de apoio',time:r.time||nowTime(),status:data.status||'Pendente',priority:r.priority||'Média',id:r.id||uid()};let at=state.records.findIndex(x=>x.id===saved.id);if(at>=0)state.records[at]=saved;else state.records.push(saved);save();close();renderList();toast('Registro salvo com sucesso.')};bindClose()}
function openMeta(){let m=state.meta;box.innerHTML=`<div class="dr-panel-head"><h2>Informações gerais do relatório</h2><button class="dr-btn" data-close>Fechar</button></div><form id="drMetaForm"><div class="dr-form-grid">${field('title','Título do relatório','text',m.title,'wide',true)}${field('date','Data de consolidação','date',m.date,'',true)}${field('objective','Objetivo do documento','textarea',m.objective,'full')}${field('audience','Público','text',m.audience)}${field('version','Versão','text',m.version)}${field('classification','Classificação','text',m.classification)}${field('owner','Responsável pelo relatório','text',m.owner,'',true)}${field('team','Time ou área','text',m.team)}${field('company','Empresa','text',m.company)}${field('notes','Observações gerais','textarea',m.notes,'full')}<div class="dr-field full"><label>Logo configurável</label><div><img class="dr-logo-preview" src="${esc(m.logo)}" alt="Logo"></div><input name="logoFile" type="file" accept="image/*"></div></div><div class="dr-modal-foot"><button type="button" class="dr-btn" data-close>Cancelar</button><button class="dr-btn primary">Salvar informações</button></div></form>`;modal.hidden=false;box.querySelector('form').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target), file=e.target.logoFile.files[0];fd.delete('logoFile');state.meta={...state.meta,...Object.fromEntries(fd)};let done=()=>{save();close();renderList();toast('Informações atualizadas.')};if(file){let rd=new FileReader();rd.onload=()=>{state.meta.logo=rd.result;done()};rd.readAsDataURL(file)}else done()};bindClose()}
function summary(){return `Foram consolidados ${state.records.length} registro(s), sendo ${state.records.filter(r=>r.status==='Concluído').length} concluído(s) e ${state.records.filter(r=>r.status!=='Concluído').length} pendente(s). Cada registro reúne solicitante, ticket, marca, teste, data da solicitação, mensagem tratada e link de referência quando informado.`}
function reportHtml(){
 let m=state.meta, gen=new Date().toLocaleString('pt-BR'), done=state.records.filter(r=>r.status==='Concluído').length, pending=state.records.length-done, links=state.records.filter(r=>r.evidenceLink).length;
 let reportLogo=m.logo&&!m.logo.includes('versao png')?m.logo:'./assets/logo-chicago-white.png'; let customLogo=`<img class="dr-report-logo" src="${esc(reportLogo)}" alt="Logo Chicago Advisory">`;
 let brand=`<div class="dr-report-brand">${customLogo||`<span class="dr-brand-mark"><i></i><i></i><i></i><i></i></span><span class="dr-brand-copy"><strong>CHICAGO</strong><span>ADVISORY PARTNERS</span></span>`}</div>`;
 let details=state.records.map((r,i)=>{let pairs=[['Nome do solicitante',r.requester],['Ticket',r.ticket],['Marca',r.institution],['Nome do teste',r.testName||r.title],['Data da solicitação',formatDate(r.date)],['Link',r.evidenceLink||r.link],['Status',r.status]].filter(x=>x[1]);return `<section class="dr-report-record"><div class="dr-record-head"><span class="dr-record-number">${i+1}</span><h3>${esc(recordTitle(r))}${r.institution?' — '+esc(r.institution):''}</h3><span class="dr-record-status">${esc(r.status)}</span></div><div class="dr-record-body"><p>${esc(recordDescription(r))}</p><div class="dr-record-grid">${pairs.map(x=>`<div><b>${esc(x[0])}</b>${esc(x[1])}</div>`).join('')}</div></div></section>`}).join('')||'<p>Nenhum registro informado.</p>';
 return `<div id="drPrintable" class="dr-report"><header class="dr-report-header">${brand}<div class="dr-report-title"><h1>${esc(m.title)}</h1><p>${esc(m.company)} • Relatório de gestão e acompanhamento operacional</p></div></header><div class="dr-cover-band"><strong>Relatório diário</strong><span>Consolidação: ${formatDate(m.date)} &nbsp; | &nbsp; Versão ${esc(m.version)}</span></div><h2>Controle do documento</h2><table><tr><td>Objetivo</td><td>${esc(m.objective)}</td></tr><tr><td>Público</td><td>${esc(m.audience)}</td></tr><tr><td>Data de consolidação</td><td>${formatDate(m.date)}</td></tr><tr><td>Classificação</td><td>${esc(m.classification)}</td></tr><tr><td>Responsável</td><td>${esc(m.owner)}</td></tr><tr><td>Time / Área</td><td>${esc(m.team)}</td></tr></table><h2>Resumo executivo</h2><div class="dr-report-kpis"><div class="dr-report-kpi"><strong>${state.records.length}</strong><span>Total de registros</span></div><div class="dr-report-kpi"><strong>${done}</strong><span>Concluídos</span></div><div class="dr-report-kpi"><strong>${pending}</strong><span>Pendentes</span></div><div class="dr-report-kpi"><strong>${links}</strong><span>Links informados</span></div></div><p class="dr-report-summary">${summary()}</p><h2>Detalhamento das solicitações e demandas</h2>${details}<footer class="dr-report-footer"><span>Chicago Advisory | Time de Serviços • Desenvolvido por Alan</span><span>Gerado em ${gen}</span></footer></div>`
}
function validReport(){if(!state.meta.date||!state.meta.owner){toast('Informe a data e o responsável antes de gerar o relatório.');openMeta();return false}return true}
function preview(){if(!validReport())return;box.className='dr-modal-box large';box.innerHTML=`<div class="dr-panel-head"><h2>Pré-visualização do relatório</h2><div class="dr-actions"><button class="dr-btn" data-close>Voltar</button><button class="dr-btn primary" data-pdf>Gerar PDF definitivo</button></div></div>${reportHtml()}`;modal.hidden=false;box.querySelector('[data-pdf]').onclick=generatePdf;bindClose()}
async function generatePdf(){if(!validReport())return;let history=JSON.parse(localStorage.getItem(HIST)||'[]'), snapshot=JSON.parse(JSON.stringify(state));snapshot.id=uid();snapshot.generatedAt=new Date().toISOString();history.unshift(snapshot);localStorage.setItem(HIST,JSON.stringify(history.slice(0,30)));let el=document.getElementById('drPrintable'),temp;if(!el){temp=document.createElement('div');temp.style.position='fixed';temp.style.left='-9999px';temp.innerHTML=reportHtml();document.body.appendChild(temp);el=temp.firstElementChild}await Promise.all([...el.querySelectorAll('img')].map(img=>img.complete&&img.naturalWidth?Promise.resolve():new Promise(resolve=>{img.onload=img.onerror=resolve})));let d=state.meta.date.split('-').reverse().join('-'),name=`Relatorio_Diario_${d}_Chicago_Advisory.pdf`;if(window.html2pdf){toast('Preparando o PDF...');await html2pdf().set({margin:[12,0,12,0],filename:name,image:{type:'jpeg',quality:.94},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy'],avoid:['.dr-report-record','tr']}}).from(el).toPdf().get('pdf').then(pdf=>{let firstPage=pdf.internal.pages[1];firstPage.unshift('q 1 0 0 1 0 34.0157 cm');firstPage.push('Q');let total=pdf.internal.getNumberOfPages();for(let page=1;page<=total;page++){pdf.setPage(page);pdf.setFontSize(7);pdf.setTextColor(110);pdf.text('Página '+page+' de '+total,196,291,{align:'right'})}}).save()}else window.print();temp?.remove()}
function review(){if(!state.records.length){toast('Adicione registros antes da revisão.');return}let changes=state.records.map(r=>{let original=recordDescription(r), suggested=original.trim().replace(/\s+/g,' ').replace(/^./,c=>c.toUpperCase());if(suggested&&!/[.!?]$/.test(suggested))suggested+='.';return{id:r.id,title:recordTitle(r),original,suggested}}).filter(x=>x.original!==x.suggested);if(!changes.length){toast('Nenhuma melhoria automática encontrada.');return}box.innerHTML=`<div class="dr-panel-head"><div><h2>Revisão de conteúdo</h2><p class="dr-note">A revisão local melhora capitalização e espaçamento sem alterar identificadores técnicos.</p></div><button class="dr-btn" data-close>Fechar</button></div>${changes.map(x=>`<h3>${esc(x.title)}</h3><div class="dr-diff"><div><b>Original</b><br>${esc(x.original)}</div><div><b>Sugerido</b><br>${esc(x.suggested)}</div></div>`).join('')}<div class="dr-modal-foot"><button class="dr-btn" data-close>Manter original</button><button class="dr-btn primary" data-apply>Aplicar sugestões</button></div>`;modal.hidden=false;box.querySelector('[data-apply]').onclick=()=>{changes.forEach(c=>state.records.find(r=>r.id===c.id).description=c.suggested);save();close();renderList();toast('Sugestões aplicadas.')};bindClose()}
function history(){let h=JSON.parse(localStorage.getItem(HIST)||'[]');box.innerHTML=`<div class="dr-panel-head"><h2>Histórico de relatórios</h2><div class="dr-actions"><button class="dr-btn danger" data-clear>Limpar histórico</button><button class="dr-btn" data-close>Fechar</button></div></div><input id="drHistorySearch" class="dr-btn" style="width:100%;margin-bottom:10px" type="search" placeholder="Pesquisar por solicitante, ticket, marca, teste ou link..."><div id="drHistoryRows">${historyRows(h)}</div>`;modal.hidden=false;box.querySelector('#drHistorySearch').oninput=e=>{let q=e.target.value.toLowerCase();box.querySelector('#drHistoryRows').innerHTML=historyRows(h.filter(x=>JSON.stringify(x).toLowerCase().includes(q)))};box.querySelector('[data-clear]').onclick=()=>{if(confirm('Deseja limpar todo o histórico?')){localStorage.removeItem(HIST);history()}};box.onclick=e=>{let row=e.target.closest('[data-hid]');if(!row)return;let item=h.find(x=>x.id===row.dataset.hid);if(e.target.dataset.hact==='open'){state=item;save();close();renderList();preview()}if(e.target.dataset.hact==='duplicate'){state={...JSON.parse(JSON.stringify(item)),meta:{...item.meta,date:today()},savedAt:null};save();close();renderList();toast('Novo relatório criado com base no histórico.')}};bindClose()}
function historyRows(h){return h.length?h.map(x=>`<div class="dr-history-row" data-hid="${x.id}"><div><b>${esc(x.meta.title)}</b><br><span class="dr-note">${formatDate(x.meta.date)} • ${esc(x.meta.owner)} • ${x.records.length} registro(s)</span></div><div class="dr-actions"><button class="dr-btn" data-hact="open">Abrir</button><button class="dr-btn" data-hact="duplicate">Usar como base</button></div></div>`).join(''):'<div class="dr-empty">Nenhum relatório gerado anteriormente.</div>'}
function bindClose(){box.querySelectorAll('[data-close]').forEach(b=>b.onclick=close)}function close(){modal.hidden=true;box.className='dr-modal-box';box.innerHTML=''}
root.addEventListener('click',e=>{let a=e.target.closest('[data-act]')?.dataset.act;if(a==='new')openRecord();if(a==='meta')openMeta();if(a==='save')save(false);if(a==='preview')preview();if(a==='pdf')generatePdf();if(a==='review')review();if(a==='history')history();let item=e.target.closest('.dr-item'),ra=e.target.dataset.row;if(!item||!ra)return;let i=state.records.findIndex(r=>r.id===item.dataset.id),r=state.records[i];if(ra==='edit')openRecord(r);if(ra==='duplicate'){let title=recordTitle(r)+' (cópia)';state.records.splice(i+1,0,{...r,id:uid(),title,testName:title});save();renderList()}if(ra==='toggle'){r.status=r.status==='Concluído'?'Pendente':'Concluído';save();renderList()}if(ra==='delete'&&confirm('Excluir este registro? Esta ação não pode ser desfeita.')){state.records.splice(i,1);save();renderList()}});
document.getElementById('drSort').onchange=renderList;let dragged;function bindDrag(){root.querySelectorAll('.dr-item').forEach(el=>{el.ondragstart=()=>{dragged=el.dataset.id;el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();let from=state.records.findIndex(r=>r.id===dragged),to=state.records.findIndex(r=>r.id===el.dataset.id);state.records.splice(to,0,state.records.splice(from,1)[0]);save();renderList()}})}
let autosave;root.addEventListener('input',()=>{state.dirty=true;clearTimeout(autosave);autosave=setTimeout(()=>save(),800)});window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});window.addEventListener('daily-report-opened',()=>{renderList()});renderList();
})();
